Declare transitive no_std deps
ivan770/tftp pull request #2
Opened 2023-01-20 02:50 UTC by kaidokert

Hi - i was trying to use this from no-std code and it seems like dependency features need to be explicitly spelled out to avoid pulling in transitive `std` deps in no-std build. Please have a look

2023-01-20 11:53 UTC, ivan770 requested changes
Thanks! Just some small nits

2023-01-20 11:53 UTC, ivan770 commented on Cargo.toml
> +ascii = { version= "1", default-features = false }
```suggestion
ascii = { version = "1", default-features = false }
```

2023-01-20 11:53 UTC, ivan770 commented on Cargo.toml
> +default = ["alloc", "ascii/std", "displaydoc/std" ]
```suggestion
default = ["alloc", "ascii/std", "displaydoc/std"]
```

2023-01-20 17:52 UTC, merged

2023-01-21 03:27 UTC, kaidokert commented
Thanks for quick merge !